version: 2

jobs:
  build:
    docker:
      - image: cimg/rust:1.55.0

    steps:
      - checkout
      - run:
          name: Install Toolchain
          command: |
            rustup toolchain install nightly-2021-09-19
            rustup override set nightly-2021-09-19
            rustup +nightly-2021-09-19 component add rustfmt-preview
            rustup +nightly-2021-09-19 component add rust-src
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt --all -- --check
      - run:
          name: Build Check
          command: cargo build